"use client";
import Link from "next/link";
import {useEffect,useState} from "react";
import type {MatchedProperty} from "@/types/property";
import {CompareButton} from "@/components/compare/CompareButton";
import {FavoriteButton} from "@/components/property/FavoriteButton";
import {ValueEstimator} from "@/components/pulse/ValueEstimator";

const AREAS=["Lanang","Buhangin","Matina","Maa","Bajada","Ecoland","Talomo","Toril","Catalunan Grande","Catalunan Pequeño"];
const TAGS=["near_schools","near_malls","near_hospitals","financing","parking"];
const shown=(v:number|null|undefined,s="")=>v==null?"Not provided":`${v}${s}`;
function visitor(){let id=localStorage.getItem("mm-visitor-id");if(!id){id=crypto.randomUUID();localStorage.setItem("mm-visitor-id",id)}return id}
function track(eventType:string,propertyIds:string[]){void fetch("/api/matcher/events",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({visitorId:visitor(),eventType,propertyIds})})}

export default function MMPulse(){const[mode,setMode]=useState<"match"|"estimate">("match");return <div className="mx-auto max-w-7xl px-6 py-8"><p className="text-sm font-bold uppercase tracking-widest text-gold-700">MM Properties intelligence</p><h1 className="mt-1 text-4xl font-bold text-navy-900">MM Pulse</h1><p className="mt-2 max-w-3xl text-lg text-navy-600">Smarter Davao property decisions for buyers, investors, and sellers—discover suitable listings or understand an indicative market range with transparent local data.</p><div className="my-7 inline-flex rounded-lg border bg-white p-1"><button onClick={()=>setMode("match")} className={`rounded-md px-5 py-2 font-semibold ${mode==="match"?"bg-navy-900 text-white":"text-navy-600"}`}>Match properties</button><button onClick={()=>setMode("estimate")} className={`rounded-md px-5 py-2 font-semibold ${mode==="estimate"?"bg-navy-900 text-white":"text-navy-600"}`}>Estimate value</button></div>{mode==="match"?<PropertyMatcher/>:<ValueEstimator/>}</div>}

function PropertyMatcher(){
 const[budget,setBudget]=useState(5e6),[familySize,setFamilySize]=useState(4),[preferredAreas,setAreas]=useState<string[]>([]),[lifestyle,setLifestyle]=useState<string[]>([]),[results,setResults]=useState<MatchedProperty[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState("");
 const toggle=(a:string[],v:string,s:(x:string[])=>void)=>s(a.includes(v)?a.filter(x=>x!==v):[...a,v]);
 async function submit(){setLoading(true);setError("");try{const r=await fetch("/api/matcher",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({budget,familySize,preferredAreas,lifestyle})}),d=await r.json();if(!r.ok)throw new Error(d.error);setResults(d.results||[]);if(d.results?.length)track("result_view",d.results.map((p:MatchedProperty)=>p.id))}catch(e){setError(e instanceof Error?e.message:"Could not find matches.")}finally{setLoading(false)}}
 const nearby=results.filter(p=>!p.outsidePreferredArea),outside=results.filter(p=>p.outsidePreferredArea);
 return <div>
  <h2 className="text-2xl font-semibold">Property matching</h2><p className="mt-2 text-navy-500">Location carries 50% of the score. Exact-area and nearby properties rank ahead of distant alternatives.</p>
  <div className="mt-6 rounded-xl border bg-white p-5"><div className="grid gap-5 md:grid-cols-2"><label>Budget: PHP {budget.toLocaleString("en-PH")}<input type="range" min={1e6} max={5e7} step={5e5} value={budget} onChange={e=>setBudget(+e.target.value)} className="mt-2 w-full"/></label><label>Family size: {familySize}<input type="range" min={1} max={10} value={familySize} onChange={e=>setFamilySize(+e.target.value)} className="mt-2 w-full"/></label></div>
   <AreaInput selected={preferredAreas} onChange={setAreas}/><Choice title="Other priorities" values={TAGS} selected={lifestyle} toggle={v=>toggle(lifestyle,v,setLifestyle)}/>
   <button onClick={submit} disabled={loading} className="mt-5 rounded-md bg-gold-500 px-5 py-3 font-semibold">{loading?"Finding matches…":"Find my matches"}</button>{error&&<p className="mt-3 text-red-600">{error}</p>}
  </div>
  {nearby.length>0&&<ResultSection title={preferredAreas.length?"Best matches in or near your chosen location":"Best matches"} properties={nearby}/>} 
  {outside.length>0&&<ResultSection title="Other options outside your preferred area" description="These properties match other needs but are more than 5 km from your selected location." properties={outside}/>} 
  {!loading&&results.length===0&&<p className="mt-8 text-center text-navy-500">Set your preferences and find matching available properties.</p>}
 </div>
}

function ResultSection({title,description,properties}:{title:string;description?:string;properties:MatchedProperty[]}){return <section className="mt-9"><h2 className="text-2xl font-semibold text-navy-900">{title}</h2>{description&&<p className="mt-1 text-sm text-navy-500">{description}</p>}<div className="mt-4 grid items-stretch gap-5 md:grid-cols-2 xl:grid-cols-3">{properties.map(p=><PropertyMatch key={p.id} property={p}/>)}</div></section>}

function PropertyMatch({property:p}:{property:MatchedProperty}){const reasonColor=p.matchScore>=80?"border-green-200 bg-green-50 text-green-950":p.matchScore>=55?"border-yellow-200 bg-yellow-50 text-yellow-950":"border-red-200 bg-red-50 text-red-950";return <article className="flex h-full flex-col overflow-hidden rounded-xl border bg-white shadow-sm">
 <Link href={`/property/${p.slug}`} onClick={()=>track("listing_click",[p.id])} className="flex flex-1 flex-col"><div className="image-zoom-frame relative h-56 overflow-hidden bg-navy-50"><img src={p.coverImageUrl||"/placeholder-property.png"} alt={p.title} className="zoomable-image h-full w-full object-cover"/><span className="absolute left-3 top-3 rounded-full bg-white/95 px-3 py-1 text-xs font-bold">{p.matchScore}% match</span></div><div className="flex flex-1 flex-col p-5"><h3 className="line-clamp-2 min-h-12 font-semibold text-navy-900">{p.title}</h3><p className="mt-2 text-xl font-bold">PHP {p.price.toLocaleString("en-PH")}</p><p className="text-sm text-navy-500">{p.barangay||p.neighborhoodName}, Davao City</p><dl className="mt-4 grid grid-cols-2 gap-2 text-sm"><Spec n="Bedrooms" v={shown(p.bedrooms)}/><Spec n="Bathrooms" v={shown(p.bathrooms)}/><Spec n="Floor area" v={shown(p.floorAreaSqm," sqm")}/><Spec n="Lot area" v={shown(p.lotAreaSqm," sqm")}/><Spec n="Parking" v={shown(p.parkingSpaces," space(s)")}/><Spec n="Availability" v={p.availability}/></dl><p className={`mt-5 rounded-lg border p-4 text-base font-medium leading-6 ${reasonColor}`}>{p.matchReason}</p></div></Link>
 <div className="mt-auto flex min-h-16 items-center justify-between gap-3 border-t bg-white px-4 py-3"><div className="flex items-center gap-2"><div onClick={()=>track("compare_click",[p.id])}><CompareButton className="relative" item={{id:p.id,slug:p.slug,title:p.title,listingIntent:p.listingIntent}}/></div><FavoriteButton propertyId={p.id} className="relative" onAction={()=>track("save_click",[p.id])}/></div><Link href={`/property/${p.slug}#contact`} onClick={()=>track("contact_click",[p.id])} className="inline-flex h-10 items-center justify-center rounded-md bg-navy-900 px-5 text-sm font-semibold text-white">Contact</Link></div>
 </article>}
function Choice({title,values,selected,toggle}:{title:string;values:string[];selected:string[];toggle:(v:string)=>void}){return <><p className="mt-5 text-sm font-medium">{title}</p><div className="mt-2 flex flex-wrap gap-2">{values.map(v=><button key={v} onClick={()=>toggle(v)} className={`rounded-full border px-3 py-1 text-sm ${selected.includes(v)?"bg-navy-900 text-white":""}`}>{v.replace(/_/g," ")}</button>)}</div></>}
function AreaInput({selected,onChange}:{selected:string[];onChange:(v:string[])=>void}){const[draft,setDraft]=useState(""),[places,setPlaces]=useState<{id:string;name:string}[]>([]);useEffect(()=>{fetch("/api/places").then(r=>r.json()).then(setPlaces).catch(()=>{})},[]);function add(){const v=draft.trim();if(v&&!selected.some(x=>x.toLowerCase()===v.toLowerCase()))onChange([...selected,v].slice(0,6));setDraft("")}return <div><p className="mt-5 text-sm font-medium">Preferred areas (most important)</p><p className="mt-1 text-xs text-navy-500">Add one or more neighborhoods, barangays, subdivisions, or landmarks.</p><div className="mt-2 flex gap-2"><input value={draft} onChange={e=>setDraft(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"||e.key===","){e.preventDefault();add()}}} list="pulse-places" placeholder="Type a location and press Enter" className="w-full rounded-md border border-navy-200 px-3 py-2"/><button type="button" onClick={add} className="rounded-md border px-4">Add</button></div><datalist id="pulse-places">{places.map(p=><option key={p.id} value={p.name}/>)}</datalist><div className="mt-2 flex flex-wrap gap-2">{selected.map(v=><button type="button" key={v} onClick={()=>onChange(selected.filter(x=>x!==v))} className="rounded-full bg-navy-900 px-3 py-1 text-sm text-white">{v} ×</button>)}</div></div>}
function Spec({n,v}:{n:string;v:string}){return <div><dt className="text-xs text-navy-400">{n}</dt><dd className="font-medium capitalize">{v}</dd></div>}
