export const dynamic = 'force-dynamic';

import {NextRequest,NextResponse} from "next/server";
import {db} from "@/lib/supabase/server";

type Comp={id:string;slug:string;title:string;price:number;rentPrice:number|null;propertyType:string;propertyTypeLabel:string;bedrooms:number|null; bathrooms:number|null;floorAreaSqm:number|null;lotAreaSqm:number|null;parkingSpaces:number|null;barangay:string|null;neighborhoodName:string|null;address:string;distanceKm:number|null;coverImageUrl:string|null;status:string};

export async function GET(){const[{rows:locations},{rows:types}]=await Promise.all([db.query({text:`SELECT name,slug FROM neighborhoods ORDER BY name`,values:[]}),db.query({text:`SELECT slug,label FROM property_types ORDER BY label`,values:[]})]);return NextResponse.json({locations,propertyTypes:types})}

export async function POST(request:NextRequest){
 try{
  const body=await request.json();const propertyType=String(body.propertyType||""),location=String(body.location||""),floorArea=positive(body.floorAreaSqm),lotArea=positive(body.lotAreaSqm),bedrooms=optional(body.bedrooms),bathrooms=optional(body.bathrooms),parking=optional(body.parkingSpaces),condition=String(body.condition||"average");
  const targetArea=propertyType==="lot-only"?lotArea:(floorArea||lotArea);
  if(!propertyType||!location||!targetArea)return NextResponse.json({error:"Choose a property type and location, then enter the applicable floor or lot area."},{status:400});
  const {rows}=await db.query<Comp>({text:`WITH target AS (SELECT centroid FROM neighborhoods WHERE slug=$2 OR lower(name)=lower($2) LIMIT 1) SELECT p.id,p.slug,p.title,p.price::float price,p.rent_price::float AS "rentPrice",pt.slug AS "propertyType",pt.label AS "propertyTypeLabel",p.bedrooms,p.bathrooms::float bathrooms,p.floor_area_sqm::float AS "floorAreaSqm",p.lot_area_sqm::float AS "lotAreaSqm",p.parking_spaces AS "parkingSpaces",p.barangay,n.name AS "neighborhoodName",p.address,p.status,(SELECT url FROM property_images pi WHERE pi.property_id=p.id ORDER BY pi.is_cover DESC,pi.sort_order LIMIT 1) AS "coverImageUrl",CASE WHEN t.centroid IS NULL THEN NULL ELSE (ST_Distance(p.location,t.centroid)/1000)::float END AS "distanceKm" FROM properties p JOIN property_types pt ON pt.id=p.property_type_id LEFT JOIN neighborhoods n ON n.id=p.neighborhood_id LEFT JOIN target t ON true WHERE pt.slug=$1 AND p.price>0 AND p.status IN('active','sold') ORDER BY CASE WHEN n.slug=$2 THEN 0 ELSE 1 END,"distanceKm" NULLS LAST,p.created_at DESC LIMIT 40`,values:[propertyType,location]});
  const usable=rows.map(c=>({...c,area:propertyType==="lot-only"?c.lotAreaSqm:(c.floorAreaSqm||c.lotAreaSqm)})).filter(c=>c.area&&c.area>0&&targetArea/c.area!<2.5&&targetArea/c.area!>0.4);
  if(usable.length<2)return NextResponse.json({error:"There are not enough comparable listings yet for this property type and location. Add more complete listings before relying on an estimate."},{status:422});
  const nearby=usable.filter(c=>c.neighborhoodName?.toLowerCase()===location.toLowerCase()||(c.distanceKm!=null&&c.distanceKm<=5));const pool=(nearby.length>=3?nearby:usable).slice(0,12);const conditionFactor:{[key:string]:number}={fixer:0.88,needs_work:0.94,average:1,good:1.05,excellent:1.1,new:1.12};
  const predictions=pool.map(c=>{let value=(c.price/Number(c.area))*targetArea;value*=1+clamp(((bedrooms??c.bedrooms??0)-(c.bedrooms??bedrooms??0))*.025,-.1,.1);value*=1+clamp(((bathrooms??c.bathrooms??0)-(c.bathrooms??bathrooms??0))*.015,-.06,.06);value*=1+clamp(((parking??c.parkingSpaces??0)-(c.parkingSpaces??parking??0))*.02,-.06,.06);value*=conditionFactor[condition]||1;return value});
  const midpoint=median(predictions),exact=pool.filter(c=>c.neighborhoodName?.toLowerCase()===location.toLowerCase()).length,complete=pool.filter(c=>c.bedrooms!=null&&(c.floorAreaSqm!=null||c.lotAreaSqm!=null)).length;const confidence=pool.length>=8&&exact>=3&&complete>=6?"high":pool.length>=4?"medium":"low";const spread=confidence==="high"?.08:confidence==="medium"?.12:.18;const pricePerSqm=midpoint/targetArea;
  const rentals=usable.filter(c=>c.rentPrice&&c.area).map(c=>Number(c.rentPrice)/Number(c.area)*targetArea);const rentMid=rentals.length>=2?median(rentals):null;
  const factors=[`${pool.length} comparable ${pool.length===1?"listing":"listings"} analyzed`,nearby.length>=3?`${nearby.length} comparables in or within 5 km of ${location}`:`Limited nearby inventory; Davao-wide comparables were also used`,`${targetArea.toLocaleString()} sqm applied at a median comparable rate`,condition!=="average"?`${condition.replace("_"," ")} condition adjustment applied`:"Average condition assumed"];
  const comparables=pool.slice(0,6).map(c=>({id:c.id,slug:c.slug,title:c.title,price:c.price,location:c.barangay||c.neighborhoodName||c.address,distanceKm:c.distanceKm==null?null:Math.round(c.distanceKm*10)/10,area:c.area,pricePerSqm:Math.round(c.price/Number(c.area)),coverImageUrl:c.coverImageUrl,status:c.status}));
  return NextResponse.json({estimate:{low:round(midpoint*(1-spread)),high:round(midpoint*(1+spread)),midpoint:round(midpoint),pricePerSqm:Math.round(pricePerSqm),confidence,factors,comparables,rental:rentMid?{low:round(rentMid*.85,100),high:round(rentMid*1.15,100),grossYieldPercent:Math.round((rentMid*12/midpoint*100)*10)/10}:null,disclaimer:"Indicative estimate only—not a licensed appraisal or guarantee of sale price. It is based mainly on current asking prices, not verified transaction prices."}});
 }catch(error){console.error("Valuation failed",error);return NextResponse.json({error:"Could not calculate an estimate."},{status:500})}
}
const optional=(v:unknown)=>v===""||v==null?null:Number.isFinite(Number(v))?Number(v):null;const positive=(v:unknown)=>{const n=optional(v);return n&&n>0?n:null};const clamp=(n:number,min:number,max:number)=>Math.max(min,Math.min(max,n));function median(values:number[]){const a=[...values].sort((x,y)=>x-y),m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}const round=(n:number,step=10000)=>Math.round(n/step)*step;

