import Link from "next/link";import{ArrowRight,BadgeCheck,Bell,MapPin,Sparkles,TrendingDown}from"lucide-react";
import{getActiveDevelopers,getHomepageNeighborhoods}from"@/lib/data";import{getPublishedPosts,BLOG_CATEGORY_LABELS}from"@/lib/blog";import{combinedFilterSearchQuery,priceReducedPropertiesQuery}from"@/lib/postgis/queries";import{db}from"@/lib/supabase/server";import type{Property}from"@/types/property";import{PropertyCard}from"@/components/property/PropertyCard";import{PropertyMiniModalCard}from"@/components/property/PropertyMiniModalCard";import{HomeSearch}from"@/components/home/HomeSearch";import{FeaturedPropertyCarousel}from"@/components/home/FeaturedPropertyCarousel";
export const dynamic="force-dynamic";
export default async function HomePage(){const[{rows},{rows:reductionRows},neighborhoods,posts,developers]=await Promise.all([db.query(combinedFilterSearchQuery({pageSize:60})),db.query(priceReducedPropertiesQuery(4)),getHomepageNeighborhoods(),getPublishedPosts(),getActiveDevelopers(true)]);const all=(rows as Property[]).filter(p=>p.status==="active"&&p.availability==="available");const featured=all.filter(p=>p.isFeatured).slice(0,6);const featuredListings=(featured.length>=3?featured:all).slice(0,6);const carouselConfigured=all.filter(p=>p.carouselEnabled).sort((a,b)=>(a.carouselOrder??100)-(b.carouselOrder??100));const carouselListings=(carouselConfigured.length?carouselConfigured:featuredListings).slice(0,12);const newest=[...all].sort((a,b)=>a.daysListed-b.daysListed).slice(0,4);const reductions=reductionRows as Property[];const financing=all.filter(p=>p.financingAvailable||p.assumeBalanceAvailable).slice(0,3);const featuredArticles=posts.filter(p=>p.isFeatured).sort((a,b)=>(a.featuredPosition||99)-(b.featuredPosition||99)).slice(0,3);const articles=featuredArticles.length?featuredArticles:posts.slice(0,1);const article=articles[0];return <main className="w-full max-w-full overflow-x-clip">
<section className="relative overflow-hidden bg-navy-900 px-6 py-16 text-white sm:py-24"><div className="absolute inset-0 opacity-20 [background-image:radial-gradient(circle_at_20%_20%,#d6a536_0,transparent_28%),radial-gradient(circle_at_80%_70%,#2563eb_0,transparent_30%)]"/><div className="relative mx-auto max-w-6xl text-center"><p className="text-sm font-bold uppercase tracking-[.22em] text-gold-300">Davao real estate, mapped locally</p><h1 className="mx-auto mt-4 max-w-4xl text-4xl font-bold leading-tight sm:text-6xl">Find a property that fits your life—not just your budget.</h1><p className="mx-auto mt-5 max-w-2xl text-base text-navy-100 sm:text-lg">Compare verified locations, discover financing opportunities, and match with homes, lots, and investments across Davao City.</p><HomeSearch/><div className="mt-5 flex flex-wrap justify-center gap-2 text-xs sm:text-sm"><Quick href="/search?financingAvailable=true">Financing available</Quick><Quick href="/search?assumeBalanceAvailable=true">Assume balance</Quick><Quick href="/search?isForeclosed=true">Foreclosed</Quick><Quick href="/search?propertyType=lot-only">Lot only</Quick></div></div></section>

<FeaturedPropertyCarousel properties={carouselListings}/>

<section className="mx-auto max-w-6xl px-6 py-14"><SectionHead eyebrow="Handpicked" title="Featured Davao properties" href="/search" link="View all properties"/><div className="mt-7 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{featuredListings.map(p=><PropertyCard key={p.id}{...cardProps(p)}/>)}</div></section>

<section className="border-y border-navy-100 bg-navy-50"><div className="mx-auto grid max-w-6xl gap-8 px-6 py-14 lg:grid-cols-[1fr_1.05fr]"><div><SectionHead eyebrow="Local intelligence" title="Top neighborhoods" href="/neighborhoods" link="Explore all"/><div className="mt-5 rounded-xl border border-navy-100 bg-white">{neighborhoods.map((n,i)=><div key={n.id} className="relative flex items-center gap-3 border-b border-navy-100 px-4 py-3 last:border-0"><span className="w-5 text-xs font-bold text-navy-300">{String(i+1).padStart(2,"0")}</span><Link href={`/neighborhoods/${n.slug}`} className="min-w-0 flex-1 font-semibold text-navy-900 hover:text-gold-700">{n.name}</Link><span className="text-xs text-navy-400">{n.listingCount} listing{n.listingCount===1?"":"s"}</span><span className="group relative"><button type="button" className="rounded-full border border-navy-200 px-2 py-1 text-xs font-semibold text-navy-600 hover:border-gold-400 focus:border-gold-400 focus:outline-none" aria-describedby={`neighborhood-price-${n.id}`}>₱/sqm</button><span id={`neighborhood-price-${n.id}`} role="tooltip" className="pointer-events-none absolute bottom-full right-0 z-50 mb-2 w-52 rounded-lg bg-navy-900 p-3 text-xs leading-5 text-white opacity-0 shadow-xl transition group-hover:opacity-100 group-focus-within:opacity-100">{n.avgPricePerSqm?`Average: PHP ${Math.round(n.avgPricePerSqm).toLocaleString("en-PH")} per sqm`:"Average price data is being collected."}</span></span></div>)}</div></div>
{article?<div className="grid gap-4">{<Link href={`/guides/${article.slug}`} className="group overflow-hidden rounded-2xl border border-navy-100 bg-white shadow-sm hover:border-gold-400 hover:shadow-lg"><div className="image-zoom-frame h-64 overflow-hidden bg-navy-100">{article.coverImageUrl?<img src={article.coverImageUrl} alt={article.title} className="zoomable-image h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-navy-400">MM Properties guide</div>}</div><div className="p-6"><p className="text-xs font-bold uppercase tracking-wide text-gold-700">Featured · {BLOG_CATEGORY_LABELS[article.category]||article.category}</p><h2 className="mt-2 text-2xl font-bold text-navy-900">{article.title}</h2><p className="mt-3 line-clamp-3 text-sm leading-6 text-navy-500">{article.excerpt||article.content}</p><span className="mt-5 inline-flex items-center gap-2 text-sm font-bold text-navy-900">Read the guide <ArrowRight size={16}/></span></div></Link>}{articles.slice(1,3).map(item=><Link key={item.id} href={`/guides/${item.slug}`} className="group grid gap-3 rounded-2xl border border-navy-100 bg-white p-3 shadow-sm hover:border-gold-400 hover:shadow-lg sm:grid-cols-[120px_1fr]"><div className="image-zoom-frame h-28 overflow-hidden rounded-xl bg-navy-100">{item.coverImageUrl?<img src={item.coverImageUrl} alt={item.title} className="zoomable-image h-full w-full object-cover"/>:<div className="flex h-full items-center justify-center text-xs text-navy-400">Guide</div>}</div><div className="min-w-0"><p className="text-[10px] font-bold uppercase tracking-wide text-gold-700">Featured · {BLOG_CATEGORY_LABELS[item.category]||item.category}</p><h3 className="mt-1 line-clamp-2 font-bold leading-5 text-navy-900 group-hover:text-gold-700">{item.title}</h3><p className="mt-1 line-clamp-2 text-xs leading-5 text-navy-500">{item.excerpt||item.content}</p></div></Link>)}</div>:<div className="rounded-2xl border border-dashed border-navy-200 bg-white p-8"><p className="font-semibold text-navy-900">Your featured article will appear here.</p><p className="mt-2 text-sm text-navy-500">Publish and feature a blog post from the content studio.</p></div>}</div></section>

<section className="mx-auto max-w-6xl px-6 py-14"><div className="grid gap-8 lg:grid-cols-2"><MarketList title="Just listed" subtitle="Fresh opportunities added to MM Properties" items={newest}/><MarketList title="Price reductions" subtitle="Properties with newly improved pricing" items={reductions} priceDown/></div></section>

<section className="bg-navy-900 px-6 py-14 text-white"><div className="mx-auto grid max-w-6xl items-center gap-8 lg:grid-cols-[1.1fr_.9fr]"><div><p className="text-sm font-bold uppercase tracking-widest text-gold-300">MM Pulse</p><h2 className="mt-3 text-3xl font-bold">Turn preferences into a smarter property shortlist.</h2><p className="mt-4 max-w-xl leading-7 text-navy-100">MM Pulse weights exact location, distance, budget, household needs, and lifestyle priorities—helping buyers and investors spend less time on listings that do not fit.</p><Link href="/matcher" className="mt-6 inline-flex items-center gap-2 rounded-lg bg-gold-500 px-5 py-3 font-bold text-navy-950"><Sparkles size={18}/>Find my matches</Link></div><div className="grid grid-cols-2 gap-3"><Metric value="50%" label="location weighting"/><Metric value="Exact pins" label="for local accuracy"/><Metric value="1–100" label="transparent match score"/><Metric value="Davao-first" label="market context"/></div></div></section>

{financing.length>0&&<section className="mx-auto max-w-6xl px-6 py-14"><SectionHead eyebrow="Flexible buying" title="Financing & assume-balance opportunities" href="/search?financingAvailable=true" link="View financing listings"/><div className="mt-7 grid gap-5 md:grid-cols-3">{financing.map(p=><PropertyCard key={p.id}{...cardProps(p)}/>)}</div></section>}

{developers.length>0&&<section className="border-y border-navy-100 bg-white px-6 py-14"><div className="mx-auto max-w-6xl"><SectionHead eyebrow="Browse by builder" title="Featured developers"/><div className="mt-7 grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">{developers.slice(0,12).map(d=><Link key={d.id} href={`/search?developerName=${encodeURIComponent(d.name)}`} title={`View ${d.listingCount} active ${d.name} listing${d.listingCount===1?"":"s"}`} className="group flex aspect-[3/2] items-center justify-center rounded-xl border border-navy-100 bg-white p-4 transition hover:-translate-y-1 hover:border-gold-400 hover:shadow-md"><img src={d.logoUrl!} alt={`${d.name} logo`} className="max-h-16 max-w-full object-contain transition group-hover:scale-105"/></Link>)}</div></div></section>}

<section className="mx-auto max-w-6xl px-6 py-14"><div className="grid gap-5 md:grid-cols-3"><Trust icon={<MapPin/>} title="Precise local pins" text="Listings use exact map coordinates instead of relying only on incomplete Philippine addresses."/><Trust icon={<BadgeCheck/>} title="Clear listing context" text="See availability, seller or agent information, pricing changes, views, saves, and days listed."/><Trust icon={<Bell/>} title="Useful buyer alerts" text="Create a free account to save homes and prepare for new-listing and price-drop alerts."/></div><div className="mt-10 grid gap-5 rounded-2xl bg-gold-50 p-7 md:grid-cols-2"><div><h2 className="text-2xl font-bold text-navy-900">Looking for a property?</h2><p className="mt-2 text-sm text-navy-600">Create an account to save listings and receive better-matched opportunities.</p><Link href="/signup" className="mt-4 inline-flex rounded-lg bg-navy-900 px-5 py-3 text-sm font-bold text-white">Create free account</Link></div><div className="border-t border-gold-200 pt-6 md:border-l md:border-t-0 md:pl-7 md:pt-0"><h2 className="text-2xl font-bold text-navy-900">Selling or representing properties?</h2><p className="mt-2 text-sm text-navy-600">List with MM Properties or apply as a verified collaborator.</p><div className="mt-4 flex flex-wrap gap-2"><Link href="/apply" className="rounded-lg bg-gold-500 px-5 py-3 text-sm font-bold text-navy-950">Apply to list a property</Link><Link href="/apply" className="rounded-lg border border-navy-300 px-5 py-3 text-sm font-bold text-navy-900">Become a collaborator</Link></div></div></div></section>
</main>}
function Quick({href,children}:{href:string;children:React.ReactNode}){return <Link href={href} className="rounded-full border border-white/20 bg-white/5 px-3 py-1.5 text-navy-100 hover:border-gold-400 hover:text-gold-300">{children}</Link>}
function SectionHead({eyebrow,title,href,link}:{eyebrow:string;title:string;href?:string;link?:string}){return <div className="flex items-end justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-gold-700">{eyebrow}</p><h2 className="mt-1 text-2xl font-bold text-navy-900 sm:text-3xl">{title}</h2></div>{href&&<Link href={href} className="hidden items-center gap-1 text-sm font-bold text-navy-700 hover:text-gold-700 sm:inline-flex">{link}<ArrowRight size={16}/></Link>}</div>}
function MarketList({title,subtitle,items,priceDown=false}:{title:string;subtitle:string;items:Property[];priceDown?:boolean}){return <div><div className="flex items-center gap-3">{priceDown&&<TrendingDown className="text-red-600"/>}<div><h2 className="text-2xl font-bold text-navy-900">{title}</h2><p className="text-sm text-navy-500">{subtitle}</p></div></div><div className="mt-5 divide-y overflow-hidden rounded-xl border border-navy-100 bg-white">{items.length?items.map(p=><PropertyMiniModalCard key={p.id} property={p} priceDown={priceDown}/>):<p className="p-6 text-sm text-navy-500">New entries will appear automatically.</p>}</div></div>}
function Metric({value,label}:{value:string;label:string}){return <div className="rounded-xl border border-white/10 bg-white/5 p-5"><p className="text-xl font-bold text-gold-300">{value}</p><p className="mt-1 text-xs text-navy-100">{label}</p></div>}
function Trust({icon,title,text}:{icon:React.ReactNode;title:string;text:string}){return <div className="rounded-xl border border-navy-100 p-6"><div className="text-gold-700">{icon}</div><h3 className="mt-4 font-bold text-navy-900">{title}</h3><p className="mt-2 text-sm leading-6 text-navy-500">{text}</p></div>}
function cardProps(p:Property){return{id:p.id,slug:p.slug,title:p.title,price:p.price,bedrooms:p.bedrooms,bathrooms:p.bathrooms,floorAreaSqm:p.floorAreaSqm,lotAreaSqm:p.lotAreaSqm,coverImageUrl:p.coverImageUrl,neighborhoodName:p.neighborhoodName,barangay:p.barangay,isForeclosed:p.isForeclosed,propertyType:p.propertyType,listingIntent:p.listingIntent,availability:p.availability,rentPrice:p.rentPrice,financingAvailable:p.financingAvailable,assumeBalanceAvailable:p.assumeBalanceAvailable,previousPrice:p.previousPrice,agentName:p.agentName,agencyName:p.agencyName,parkingSpaces:p.parkingSpaces,daysListed:p.daysListed,viewCount:p.viewCount,saveCount:p.saveCount}}
